### ISSUE TITLE
Possibly flaky test in VerticalListTests

### ISSUE THREAD

**Issue by novak-dev** [google-developer-training/android-basics-kotlin-dogglers-app#10]
**URL of codelab**
[Dogglers ](https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app)

**In which task and step of the codelab can this issue be found?**
Running the tests at the end

**Describe the problem**
The test vertical_scrolling is failing for me. I don't think its a bug with my application code though because when I put a sleep after performing the swipe it is passing the test. So it looks like a race condition when the view is being checked if its displayed before the swipe animation is completed. Error:

`
androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
     Got: "MaterialTextView{id=2131230864, res-name=dog_name, visibility=VISIBLE, width=115, height=71, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@fb2e21e, tag=null, root-is-layout-requested=false, has-input-connection=false, x=21.0, y=530.0, text=Faye, input-type=0, ime-target=false, has-links=false}"
`

**Steps to reproduce?**
Run the vertical_scrolling test on an emulator. I am using Pixel 2 API 28 (Android 9). All animations have been disabled

**Versions**
Android Studio Arctic fox 2020.3.1 patch 4
Api level 28

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by johnmcwade** [comment]
Same experience here with a physical Pixel 2 w/ Android 11.
A delay of 1000ms after swipeUp allowed the test to pass.
 
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 1, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1

**Comment by RomanRC99** [comment]
Same problem, delay of 1000 ms helps as well.
