### ISSUE TITLE
Android Basics: Dogglers app

### ISSUE THREAD

**Issue by Yeongjo-Jeong** [google-developer-training/android-basics-kotlin-dogglers-app#12]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
        
        GridLayout id incompatible with latest Android Studio.

        Warning shown --
        This operation requires the library androidx.gridlayout:gridlayout:+.
        
        Problem: Inconsistencies in the existing project dependencies found.
        Version incompatibility between:
        -   com.google.android.material:material:1.3.0@aar
        and:
        -   androidx.fragment:fragment-ktx:1.3.3@aar
        
        With the dependency:
        -   androidx.annotation:*:1.1.0
        versus:
        -   androidx.annotation:*:2.0.0
        
        The project may not compile after adding this library.
        Would you like to add it anyway?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@Yeongjo-Jeong 
Thank you for reaching out to us. Recently the Gradle and libraries numbers versions were updated. Please try to clone the updated branch and feel free to re-open the ticket if you still face with the same issues.
