### ISSUE TITLE
Android Basics: Dogglers app

### ISSUE THREAD

**Issue by arjanga** [google-developer-training/android-basics-kotlin-dogglers-app#19]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#3

**In which task and step of the codelab can this issue be found?**
In the testing of the dogglers app phase

**Describe the problem**
The BaseTest.kt file has incorrect info in the function checkFirstPosition(). Currently the method hasListItem(<name>, <age>, <hobbies>, <imageResource>) is where the error resides. The <age> and <hobbies> inputs have the string "Age: 7" and "Hobbies: sunbathing" when it should just be "7" and "sunbathing". The hardcoded strings of the actual property names in this is causing the tests to fail.

**Steps to reproduce?**
1. Build the project as instructed by the codelab
2. run the first test suite
3. One test will pass and all others will fail. You will see that the error will say something along the lines that "Age: 7" cannot be found. That is because in the data package's DataSource.kt file, all ages are "<number>" and not "Age: <number>". The same goes for hobbies.

**Versions**
_Android Studio version:_  2021.1
_API version of the emulator:_ API 32

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@arjanga 
Thank you for reaching out to us. The issue is fixed along with other updates in the branch.
