### ISSUE TITLE
Android Basics: Dogglers app - issue on androidTest

### ISSUE THREAD

**Issue by vj-abishek** [google-developer-training/android-basics-kotlin-dogglers-app#26]
**URL of codelab**
[Project: Doggler app](https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#2
)

**In which task and step of the codelab can this issue be found?**
While running my test cases

**Describe the problem**
There are four test cases
1. ButtonTests - which has no issue
2. The rest three has one issue on `checkFirstPosition` function

### Actual code:
```kotlin
 fun checkFirstPosition() {
        hasListItemContent("Tzeitel", "7", "sunbathing",
            R.drawable.tzeitel)
    }
```

### But the function should be:
```kotlin
 fun checkFirstPosition() {
        hasListItemContent("Tzeitel", "Age: 7", "Hobbies: sunbathing",
            R.drawable.tzeitel)
    }
```

![image](https://user-images.githubusercontent.com/43115551/170868385-b5c419af-2233-4afc-9e0d-33a126b26ffb.png)

In the colab it has `age` and `hobbies` before the actual content

So I think the `checkFirstPosition` test case is wrong

**Steps to reproduce?**
1. Go to  `androidTest`
2. Run any test case except `ButtonTests` such as `HorizontalListTests` 
3. See error...

![image](https://user-images.githubusercontent.com/43115551/170868552-6e963090-a5f1-452a-bf8c-6cec1ec70f89.png)

**Comment by lixoten** [comment]
Seems this has been fixed, but it is not part of the ZIP file that gets downloaded
