### ISSUE TITLE
Android Basics: Dogglers app

### ISSUE THREAD

**Issue by DatTrannn** [google-developer-training/android-basics-kotlin-dogglers-app#34]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#3

**In which task and step of the codelab can this issue be found?**
Test Your App

**Describe the problem**
checkFirstPosition function of BasicTest class must be
`
   fun checkFirstPosition() {
        hasListItemContent("Tzeitel", "Age: 7", "Hobbies: sunbathing",
            R.drawable.tzeitel)
    }` so it could match with the required display 

**Versions**
_Android Studio version:_  32

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
The old checkFirstPosition() function
![image](https://user-images.githubusercontent.com/49610104/176959049-fa820105-827c-4832-a9e1-bdae866e58b5.png)

**Comment by Himanshu-kumar-gupta** [comment]
Thanks for the fix! 
I was having the same issue
