### ISSUE TITLE
Android Basics: Dogglers app

### ISSUE THREAD

**Issue by asaywitz** [google-developer-training/android-basics-kotlin-dogglers-app#36]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#2

**In which task and step of the codelab can this issue be found?**
3. Get started]

**Describe the problem**
If you click the Grid Button, it doesn't look correct because the ViewType passed to onCreateViewHolder is 0 so depending on how you coded onCreateViewHolder you will most likely default to the wrong layout. For example I had this

        val layoutResourceId = when(viewType) {
            Layout.GRID -> R.layout.grid_list_item
            else -> R.layout.vertical_horizontal_list_item
        }

based on reading the codelab. Originally I had this version below since normally I don't like leaving things to chance and looking back  I wish I had kept it since it would have saved me some debugging time :)

        val layoutResourceId = when(viewType) {
            Layout.HORIZONTAL, Layout.VERTICAL -> R.layout.vertical_horizontal_list_item
            Layout.GRID -> R.layout.grid_list_item
            else -> throw IllegalArgumentException("Unknown viewType $viewType")
        }

The fix was very easy I just added to DogCardAdapter:

    override fun getItemViewType(position: Int): Int {
        return layout;
    }

Then everything was good again :)

**Steps to reproduce?**
1. Run the app 
2. Click Grid button
3. See that the layout looks bad. In my case I was still using R.layout.vertical_horizontal_list_item instead of R.layout.grid_list_item.

**Versions**
Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 18, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.intellij.plugins.markdown (212.5457.16), Dart (212.5744), io.flutter (69.0.2)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screen Shot 2022-07-09 at 8 12 11 AM](https://user-images.githubusercontent.com/5882475/178109333-6091823c-7acb-4deb-bf34-37e1134a9b51.png)

**Comment by wlai177** [comment]
Thanks. I was running into this issue too. Another solution is to use the "layout" variable instead of "viewType" as the condition for the _when()_ statement.
