### ISSUE TITLE
Android Basics: Dogglers app

### ISSUE THREAD

**Issue by Fourfold** [google-developer-training/android-basics-kotlin-dogglers-app#39]
**URL of codelab** 
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#3

**In which task and step of the codelab can this issue be found?** 
step 4: Test you app

**Describe the problem**
there is a problem in the following instrumentation tests provided in the github download:
```
horizontal_scroll_content_at_first_position()   //can be found in HorizontalListTests.kt
vertical_scroll_content_at_first_position()   //can be found in VerticalListTests.kt
```
these two tests use the same function which is:
`checkFirstPosition()`
which in turn calls the following function:
`hasListItemContent(name: String, age: String, hobbies: String, imageResource: Int)`
the issue is that the function cannot find a textView with the expected value for the age("7") and hobbies("sunbathing") of the dog (Tzeitel)
to fix this test I had to change the expected value to the whole textView text, in other words the expected value for age is "Age: 7" not just "7", actually wrote like this:
```
onView(withText("Age: $age"))
            .check(matches(isDisplayed()))
```
and the same goes for the hobbies ("Hobbies: $hobbies")

**Steps to reproduce?**
run the instrumentation tests "provided on github" on a working version of the Dogglers app

**Versions**
_Android Studio version:_  2021.2.1 patch 1
I used my android phone to run the app

P.S.
I also had problems in the `vertical_scrolling()` and `horizontal_scrolling()` instrumentation tests, so I applied the Espresso setup instructions as provided in this link https://developer.android.com/training/testing/espresso/setup#set-up-environment
after applying, the `vertical_scrolling()` test worked but the `horizontal_scrolling()` test did not work with other tests; it sometimes worked when I run it on its own. this may be an issue with my phone, just wanted to let you know

Thank you for this amazing course and your continuous support :)

**Comment by wemorgan-zoho-eu** [comment]
@Fourfold: I had the same problems as you, but testing on an emulator.

If I debug `horizontal_scrolling()` (to slow things down) I can see that the swipe is going too far, so that '**Frankie**' is not visible (but the next dog '**Nox**' is visible).

Also, although it's a terrible hack, I've found that the tests can be made to pass (after changing '**Frankie**' to '**Nox**') by inserting a wait between the swipe and the check. So for me these tests **always** pass:
```
    @Test
    fun `horizontal_scrolling`() {
        onView(withId(R.id.horizontal_recycler_view))
            .perform(swipeLeft())
        Thread.sleep(1000)
        onView(withText("Nox")).check(matches(isDisplayed()))
    }

    @Test
    fun `vertical_scrolling`() {
        onView(withId(R.id.vertical_recycler_view))
                .perform(swipeUp())
        Thread.sleep(1000)
        onView(withText("Faye")).check(matches(isDisplayed()))
    }
 ```

**Comment by IlyaVassyutovich** [comment]
Can confirm problems with `horizontal_scrolling`-test. `swipeLeft` on recycler view in my environment swipes too fast or too far (see screenshot).

I'm using Pixel 5 API 31 emulator (1080x2340).

<details>

<summary>Screenshot</summary>

![Screenshot_20220817_123223](https://user-images.githubusercontent.com/6738342/185086209-1c3a024f-5884-497a-9452-a227463e85c6.png)

</details>
