### ISSUE TITLE
function checkFirstPosition() will always fail the test

### ISSUE THREAD

**Issue by vincely** [google-developer-training/android-basics-kotlin-dogglers-app#40]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#3

**In which task and step of the codelab can this issue be found?**
The test functions `grid_list_content_at_first_position`, `horizontal_scroll_content_at_first_position` and `vertical_scroll_content_at_first_position` will never pass because of the function `checkFirstPosition()` in `BaseTest.kt` 

**Describe the problem**
In the `DogCardAdapter.kt` you are supposed to pass the arguments `dog.age` and `dog.hobbies` to the String constant in `strings.xml` by doing something like:
`holder.dogAge?.text = resources?.getString(R.string.dog_age, dog.age)`

However, the tests check if the arguments are displayed instead of checking if the actual modified string is displayed. 
For example: the String that is displayed is: "Age: 7", while the test checks if the string is actually "7". 

**Steps to reproduce?**
Run either GridListTests, HorizontalTests or VerticalListTests

**Versions**
_Android Studio version:_ 2021.2.1 Patch 1
_API version of the emulator:_ /

**Additional information**
The tests will pass if you modify `hasListItemContent()` in `BaseTest.kt`. I basically use `containsString` to check if the String is part of the String that is displayed instead of looking for an exact match. 

```
import org.hamcrest.core.StringContains.containsString

    private fun hasListItemContent(name: String, age: String, hobbies: String, imageResource: Int) {
        onView(withText(name))
            .check(matches(isDisplayed()))
        onView(withText(containsString(age)))
            .check(matches(isDisplayed()))
        onView(withText(containsString(hobbies)))
            .check(matches(isDisplayed()))
        onView(withDrawable(imageResource))
            .check(matches(isDisplayed()))
    }
```

Alternatively you could also modify `checkFirstPostition()` to match the displayed String:

    fun checkFirstPosition() {
        hasListItemContent("Tzeitel", "Age: 7", "Hobbies: sunbathing",
            R.drawable.tzeitel)
    }

**Original Code**
```
    private fun hasListItemContent(name: String, age: String, hobbies: String, imageResource: Int) {
        onView(withText(name))
            .check(matches(isDisplayed()))
        onView(withText(age))
            .check(matches(isDisplayed()))
        onView(withText(hobbies))
            .check(matches(isDisplayed()))
        onView(withDrawable(imageResource))
            .check(matches(isDisplayed()))
    }
```

```
    fun checkFirstPosition() {
        hasListItemContent("Tzeitel", "7", "sunbathing",
            R.drawable.tzeitel)
    }
```

**Comment by vincely** [comment]
issue has been mentioned a lot of times already. It is not resolved yet, but I've closed it to reduce the amount of posts that have to be reviewed.

**Comment by Hgnis-Raknahs** [comment]
it's good but you have to apply it on test file also.
