### ISSUE TITLE
Android Basics: Dogglers app

### ISSUE THREAD

**Issue by sluschman** [google-developer-training/android-basics-kotlin-dogglers-app#42]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#2

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
After I downloaded the code and opened it in Android Studio, it refuses to run the app and about half of the code is in red. How do I tackle the problem? I've no clue where to start... Thanks!

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ bumblebee 2021.1.1
_API version of the emulator:_ 26 (Pixel2)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ElisaWissemann** [comment]
Hello,
in the tool window bar you can find a Problems-tab -> see https://developer.android.com/studio/intro, there is your first hint about the issue. 
It might help to read the documentation on how to debug your app:
https://developer.android.com/studio/run/rundebugconfig
https://developer.android.com/studio/debug

I hope this helps you to keep on going. 
Happy coding!
E.
