### ISSUE TITLE
Android Basics: Dogglers app

### ISSUE THREAD

**Issue by moisedk** [google-developer-training/android-basics-kotlin-dogglers-app#9]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-dogglers-app?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-dogglers-app#2

**In which task and step of the codelab can this issue be found?**
The initial code
**Describe the problem**
Android complains at runtime that since MaterialCardView is used as the root layout for the list item view, the app must use Theme.MaterialComponents or one of its descendants. After I double-checked the /vales/themes folder, the AppTheme is Theme.MaterialComponents.DayNight.DarkActionBar. Would that be an issue  of compatibility?
Using androidx.cardview.widget.CardView work fine, and all tests passed

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  Bumblebee
_API version of the emulator:_  30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot from 2022-01-27 01-50-20](https://user-images.githubusercontent.com/56738242/151308406-ae00566b-4597-419a-b872-67aa387bb17a.png)
![Screenshot from 2022-01-27 01-50-35](https://user-images.githubusercontent.com/56738242/151308437-dec63c2e-e419-4c69-9b1d-56d90226b680.png)

**Comment by beersheba** [comment]
Resolved for me by adding
```android:theme="@style/Theme.MaterialComponents.DayNight"```
to MaterialCardView widget in both list item layouts.
